# Built with Jekyll 3.2.0
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Set encoding to UTF-8
encoding: utf-8

# Markdown specs
markdown: kramdown

collections:
  texts:
    output: true

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               Insurgencia 2.0
tagline:             construcción de Paz a través de Meme
description:         Insurgencia 2.0 es una herramienta para docentes y líderes sociales para pensar como utilizar el Meme como herramienta de construcción de paz.
url:                 https://github.com/elotroalex/ed
baseurl:             '/insurgencia2.0'

# About/contact
author:
  name:              Joao Gabriel Almeida
  url:
  email:             jgabrielrtalmeida@gmail.com

# Custom vars
version:             0.0.5

# Exclude optional folder
exclude: [optional]

# Gems
gems: ['jekyll/scholar']

# Scholar
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/ed/bibliography.html"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
